# Generated by Django 3.2.15 on 2022-08-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, default='../default_post_e14ubs.jpg', upload_to='images/')),
                ('environment', models.CharField(choices=[('coastal', 'Coastal'), ('woodland', 'Woodland'), ('countryside', 'Countryside'), ('moorland', 'Moorland'), ('hill', 'Hill'), ('mountain', 'Mountain'), ('peak', 'Peak'), ('other', 'Other')], default=0, max_length=55)),
                ('wc', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=0, max_length=20)),
                ('dog_friendly', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=0, max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default=0, max_length=55)),
                ('length', models.CharField(max_length=55)),
                ('duration', models.CharField(max_length=55)),
                ('content', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
