# Generated by Django 3.2.15 on 2022-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220915_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='environment',
            field=models.CharField(choices=[('coastal', 'Coastal'), ('woodland', 'Woodland'), ('countryside', 'Countryside'), ('moorland', 'Moorland'), ('hill', 'Hill'), ('mountain', 'Mountain'), ('peak', 'Peak'), ('city', 'City'), ('other', 'Other')], default='other', max_length=55),
        ),
    ]
