# Generated by Django 3.2.15 on 2022-08-25 10:48

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=location_field.models.plain.PlainLocationField(editable=False, max_length=63),
        ),
    ]
