# Generated by Django 3.2.15 on 2022-09-16 07:48

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220916_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
