# Generated by Django 3.2.15 on 2022-09-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('photography', 'Photography'), ('artwork', 'Artwork')], default='artwork', max_length=55),
        ),
    ]
