# Generated by Django 3.2.15 on 2022-09-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-updated_on']},
        ),
    ]
